version: "1.0"
groups:
  dev:
    targets:
      runserver:
        help: Run the server application
        run: |
          sugar down
          sugar build
          sugar ext restart

      tests:
        help: Run the server application
        run: |
          ./vendor/bin/phpunit tests/SettingsTest.php
          ./vendor/bin/phpunit tests/PersonTest.php
          ./vendor/bin/phpunit tests/SubscriptionTest.php
          ./vendor/bin/phpunit tests/EventTest.php
          ./vendor/bin/phpunit tests/EventSessionTest.php
          ./vendor/bin/phpunit tests/AttendanceTest.php
          # ./vendor/bin/phpunit tests/EmailTest.php
