version: "1.0"
groups:
  dev:
    targets:
      runserver:
        help: Run the server application
        run: |
          cd src
          # echo "HOST_ADDRESS=http://localhost:8081" > .env
          php -S localhost:8081

      tests:
        help: Run the server application
        run: |
          ./vendor/bin/phpunit tests/SettingsTest.php
          ./vendor/bin/phpunit tests/PersonTest.php
          ./vendor/bin/phpunit tests/SubscriptionTest.php
          ./vendor/bin/phpunit tests/AttendanceTest.php
          # ./vendor/bin/phpunit tests/EmailTest.php
