version: '3.3'

services:
  web:
    build:
      context: ..
      dockerfile: ./containers/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    ports:
      - ${HOST_PORT}:80
    user: "${UID}:${GID}"
    volumes:
      - ../src:/app
